'use client';
import { useRouter } from 'next/navigation';

export default function PrivacyPage() {
  const router = useRouter();
  
  return (
    <div style={{ minHeight: '100dvh', paddingBottom: 60, color: 'var(--text-primary)' }}>
      <nav className="navbar">
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '0 16px', display: 'flex', alignItems: 'center', height: 56 }}>
          <button onClick={() => router.push('/')} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontFamily: 'var(--font-devanagari)' }}>
            ‹ मागे (Back)
          </button>
          <span style={{ marginLeft: 'auto', fontFamily: 'var(--font-devanagari)', fontWeight: 700, color: 'var(--saffron-400)' }}>
            Privacy Policy
          </span>
        </div>
      </nav>

      <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 16px', lineHeight: 1.6 }}>
        <h1 style={{ color: 'var(--saffron-500)', marginBottom: 20 }}>Privacy Policy</h1>
        <p style={{ color: 'var(--text-muted)', marginBottom: 20 }}>Last updated: July 20, 2026</p>
        
        <h2 style={{ fontSize: '1.2rem', marginTop: 24, marginBottom: 12 }}>1. Information We Collect</h2>
        <p style={{ marginBottom: 16 }}>
          To generate your astrological reports and biodata, we collect the following personal information: Full Name, Date of Birth, Time of Birth, Place of Birth, Gender, Contact Number, and Email Address. We also temporarily collect payment transaction IDs generated by Razorpay.
        </p>

        <h2 style={{ fontSize: '1.2rem', marginTop: 24, marginBottom: 12 }}>2. How We Use Your Information</h2>
        <p style={{ marginBottom: 16 }}>
          The data collected is strictly used to:
        </p>
        <ul style={{ paddingLeft: 20, marginBottom: 16 }}>
          <li>Generate accurate astrological charts and biodata PDFs.</li>
          <li>Send the generated PDF reports to your email or WhatsApp.</li>
          <li>Provide customer support.</li>
        </ul>

        <h2 style={{ fontSize: '1.2rem', marginTop: 24, marginBottom: 12 }}>3. Data Storage and Security</h2>
        <p style={{ marginBottom: 16 }}>
          We prioritize the security of your data. Your birth details and generated reports are stored securely in our database. We do not sell, rent, or share your personal data with third-party advertising agencies.
        </p>

        <h2 style={{ fontSize: '1.2rem', marginTop: 24, marginBottom: 12 }}>4. Third-Party Services</h2>
        <p style={{ marginBottom: 16 }}>
          We use Razorpay for processing payments. We do not store your credit card, debit card, or UPI PIN details on our servers. All payment processing is securely handled by Razorpay. We use Resend to deliver your PDF emails.
        </p>

        <h2 style={{ fontSize: '1.2rem', marginTop: 24, marginBottom: 12 }}>5. Data Deletion</h2>
        <p style={{ marginBottom: 16 }}>
          If you wish to have your data or generated PDFs permanently deleted from our servers, you may contact our support team.
        </p>
      </div>
    </div>
  );
}
