"""initial_schema

Revision ID: 2b735dc1e338
Revises: 
Create Date: 2026-07-19 16:31:21.860926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b735dc1e338'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('time_of_birth', sa.Time(), nullable=True),
    sa.Column('time_accuracy', sa.Enum('exact', 'approximate', 'unknown', name='time_accuracy_enum'), nullable=False),
    sa.Column('place_text', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('tz_iana', sa.String(length=100), nullable=False),
    sa.Column('rahu_mode', sa.Enum('true_node', 'mean_node', name='rahu_mode_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geocode_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_normalized', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('tz_iana', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geocode_cache_query_normalized'), 'geocode_cache', ['query_normalized'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_table('kundalis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('birth_profile_id', sa.UUID(), nullable=False),
    sa.Column('rashi_value', sa.Integer(), nullable=True),
    sa.Column('nakshatra_value', sa.Integer(), nullable=True),
    sa.Column('pada', sa.Integer(), nullable=True),
    sa.Column('lagna_value', sa.Integer(), nullable=True),
    sa.Column('lagna_reliable', sa.Boolean(), nullable=False),
    sa.Column('gana', sa.String(length=50), nullable=True),
    sa.Column('nadi', sa.String(length=50), nullable=True),
    sa.Column('varna', sa.String(length=50), nullable=True),
    sa.Column('chart_d1_svg', sa.Text(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('planet_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('navamsa_svg', sa.Text(), nullable=True),
    sa.Column('mangal_dosha', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dasha', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('written_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('resume_token', sa.String(length=64), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['birth_profile_id'], ['birth_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kundalis_birth_profile', 'kundalis', ['birth_profile_id'], unique=False)
    op.create_index(op.f('ix_kundalis_paid'), 'kundalis', ['paid'], unique=False)
    op.create_index('ix_kundalis_paid_created', 'kundalis', ['paid', 'created_at'], unique=False)
    op.create_index(op.f('ix_kundalis_resume_token'), 'kundalis', ['resume_token'], unique=True)
    op.create_table('biodatas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kundali_id', sa.UUID(), nullable=True),
    sa.Column('personal_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('horoscope_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('resume_token', sa.String(length=64), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kundali_id'], ['kundalis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biodatas_resume_token'), 'biodatas', ['resume_token'], unique=True)
    op.create_table('matchings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bride_kundali_id', sa.UUID(), nullable=True),
    sa.Column('groom_kundali_id', sa.UUID(), nullable=True),
    sa.Column('bride_birth_profile_id', sa.UUID(), nullable=True),
    sa.Column('groom_birth_profile_id', sa.UUID(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('total_max', sa.Integer(), nullable=False),
    sa.Column('bride_manglik', sa.Boolean(), nullable=True),
    sa.Column('groom_manglik', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('koota_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dosha_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict_mr', sa.Text(), nullable=True),
    sa.Column('verdict_en', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('resume_token', sa.String(length=64), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bride_birth_profile_id'], ['birth_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bride_kundali_id'], ['kundalis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['groom_birth_profile_id'], ['birth_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['groom_kundali_id'], ['kundalis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchings_paid'), 'matchings', ['paid'], unique=False)
    op.create_index(op.f('ix_matchings_resume_token'), 'matchings', ['resume_token'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Enum('kundali', 'matching', 'biodata', 'bundle', name='product_type_enum'), nullable=False),
    sa.Column('kundali_id', sa.UUID(), nullable=True),
    sa.Column('matching_id', sa.UUID(), nullable=True),
    sa.Column('biodata_id', sa.UUID(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('created', 'attempted', 'paid', 'failed', 'refunded', name='order_status_enum'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_phone', sa.String(length=15), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['biodata_id'], ['biodatas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kundali_id'], ['kundalis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matching_id'], ['matchings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_orders_razorpay_payment_id'), 'orders', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_payment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_matchings_resume_token'), table_name='matchings')
    op.drop_index(op.f('ix_matchings_paid'), table_name='matchings')
    op.drop_table('matchings')
    op.drop_index(op.f('ix_biodatas_resume_token'), table_name='biodatas')
    op.drop_table('biodatas')
    op.drop_index(op.f('ix_kundalis_resume_token'), table_name='kundalis')
    op.drop_index('ix_kundalis_paid_created', table_name='kundalis')
    op.drop_index(op.f('ix_kundalis_paid'), table_name='kundalis')
    op.drop_index('ix_kundalis_birth_profile', table_name='kundalis')
    op.drop_table('kundalis')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_geocode_cache_query_normalized'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    op.drop_table('birth_profiles')
    # ### end Alembic commands ###
