"""Add manglik severity to matching

Revision ID: 56bc1ca8edfd
Revises: 2b735dc1e338
Create Date: 2026-07-21 01:58:26.430761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bc1ca8edfd'
down_revision: Union[str, None] = '2b735dc1e338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('bride_manglik_severity', sa.String(length=20), nullable=True))
    op.add_column('matchings', sa.Column('groom_manglik_severity', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchings', 'groom_manglik_severity')
    op.drop_column('matchings', 'bride_manglik_severity')
    # ### end Alembic commands ###
